name:                hafar
version:             0.1.0.0
github:              "Soupstraw/hafar"
license:             BSD3
author:              "Joosep Jääger"
maintainer:          "Joosep Jääger"
copyright:           "2019 Joosep Jääger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Affine arithmetic library for Haskell
category:            Numeric

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:    Hafar is an affine arithmetic library for Haskell.
                It is an efficient way to work with ranges of values or imprecise values.

dependencies:
- base >= 4.12 && < 4.14
- intervals >= 0.8 && < 0.9
- mtl >= 2.2 && < 2.3

library:
  source-dirs:     src
  exposed-modules:
  - Numeric.AffineForm
  - Numeric.AffineForm.ExplicitRounding

tests:
  hafar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hafar
    - QuickCheck >= 2.13 && < 2.14
