name:                hafar
version:             0.1.0.0
github:              "Soupstraw/hafar"
license:             BSD3
author:              "Joosep Jääger"
maintainer:          "Joosep Jääger"
copyright:           "2020 Joosep Jääger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Hafar is an affine arithmetic library for Haskell.
  Affine arithmetic is an improvement of interval arithmetic.

  = Examples
  The following code example shows how subtracting the same value from itself in affine arithmetic results in zero.

  @
  import Numeric.Interval

  a1 = do
    -- Create a new instance of an affine form
    x <- newFromInterval $ 1...3
    -- Create another instance of an affine form covering the same interval
    y <- newFromInterval $ 1...3
    return $ x - y

  evalInterval a1
  -- Interval (-2) 2

  a2 = do
    -- Here we only use a single instance of an affine form
    x <- newFromInterval $ 1...3
    return $ x - x

  evalInterval a2
  -- Interval 0 0
  @

dependencies:
- base >= 4.7 && < 5
- intervals >= 0.8 && < 1
- QuickCheck >= 2.13 && < 3
- random >= 1.1 && < 2
- mtl >= 2.2 && < 3

library:
  source-dirs: src

tests:
  hafar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hafar
